# Generated by Django 3.1.4 on 2020-12-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='divisions',
            new_name='division',
        ),
    ]
