# Generated by Django 3.1.4 on 2020-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201217_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyuser',
            old_name='company_link',
            new_name='website_link',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='comapny_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
