# Generated by Django 3.1.4 on 2020-12-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201221_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company-photos/'),
        ),
    ]
